# This is a basic workflow to help you get started with Actions

name: CI2

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_in_env:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: checkout code
        uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: checkout default env
        run: env
      - name: print env
        run: echo $GITHUB_REPOSITORY
      - name: test with python
        run: python env.py
  # build_on_windows:
  #   # The type of runner that the job will run on
  #   runs-on: windows-latest
  #   steps:
  #    - name: run multi-line-script
  #      run: |
  #        echo "hello github actions"
  #        Get-Date
    