name: Workflow Secrets Example
on: workflow_dispatch

env:
  DB_U: test  # 直接定义明文环境变量

jobs:
  test-secrets:  # 作业名称无空格
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 正确缩进

      - name: Print environment variable U
        run: echo "u=${{ env.DB_U }}"  # 引用环境变量

      - name: Print secret P
        run: echo "p=${{ secrets.DB_PASSWORD }}"  # 直接引用密钥
